LIB_INCLUDES   := -I$(PROJECT_ROOT)/lib/

HAL_INCLUDES	 := -I$(PROJECT_ROOT)/hal/
SIM_INCLUDES     := -I$(PROJECT_ROOT)/sim/
TEST_INCLUDES    := -I$(PROJECT_ROOT)/tests/common/
SIMTEST_INCLUDES := $(TEST_INCLUDES) $(SIM_INCLUDES) $(LIB_INCLUDES)
