// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: development.proto

#include "development.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace protocols {
namespace development {
PROTOBUF_CONSTEXPR RouteResponse::RouteResponse(
    ::_pbi::ConstantInitialized) {}
struct RouteResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RouteResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~RouteResponseDefaultTypeInternal() {}
  union {
    RouteResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RouteResponseDefaultTypeInternal _RouteResponse_default_instance_;
}  // namespace development
}  // namespace protocols
static ::_pb::Metadata file_level_metadata_development_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_development_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_development_2eproto = nullptr;

const uint32_t TableStruct_development_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::protocols::development::RouteResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::protocols::development::RouteResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::protocols::development::_RouteResponse_default_instance_._instance,
};

const char descriptor_table_protodef_development_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\021development.proto\022\025protocols.developme"
  "nt\032\rrouting.proto\"\017\n\rRouteResponse2[\n\013De"
  "velopment\022L\n\010SetRoute\022\030.protocols.routin"
  "g.Route\032$.protocols.development.RouteRes"
  "ponse\"\000B0Z.github.com/JHU-Delivery-Robot"
  "/Server/protocolsb\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_development_2eproto_deps[1] = {
  &::descriptor_table_routing_2eproto,
};
static ::_pbi::once_flag descriptor_table_development_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_development_2eproto = {
    false, false, 225, descriptor_table_protodef_development_2eproto,
    "development.proto",
    &descriptor_table_development_2eproto_once, descriptor_table_development_2eproto_deps, 1, 1,
    schemas, file_default_instances, TableStruct_development_2eproto::offsets,
    file_level_metadata_development_2eproto, file_level_enum_descriptors_development_2eproto,
    file_level_service_descriptors_development_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_development_2eproto_getter() {
  return &descriptor_table_development_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_development_2eproto(&descriptor_table_development_2eproto);
namespace protocols {
namespace development {

// ===================================================================

class RouteResponse::_Internal {
 public:
};

RouteResponse::RouteResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:protocols.development.RouteResponse)
}
RouteResponse::RouteResponse(const RouteResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  RouteResponse* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:protocols.development.RouteResponse)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData RouteResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*RouteResponse::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata RouteResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_development_2eproto_getter, &descriptor_table_development_2eproto_once,
      file_level_metadata_development_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace development
}  // namespace protocols
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::protocols::development::RouteResponse*
Arena::CreateMaybeMessage< ::protocols::development::RouteResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::protocols::development::RouteResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
