// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: development.proto

#include "development.pb.h"
#include "development.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace protocols {
namespace development {

static const char* Development_method_names[] = {
  "/protocols.development.Development/SetRoute",
};

std::unique_ptr< Development::Stub> Development::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Development::Stub> stub(new Development::Stub(channel, options));
  return stub;
}

Development::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SetRoute_(Development_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Development::Stub::SetRoute(::grpc::ClientContext* context, const ::protocols::routing::Route& request, ::protocols::development::RouteResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::protocols::routing::Route, ::protocols::development::RouteResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetRoute_, context, request, response);
}

void Development::Stub::async::SetRoute(::grpc::ClientContext* context, const ::protocols::routing::Route* request, ::protocols::development::RouteResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::protocols::routing::Route, ::protocols::development::RouteResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetRoute_, context, request, response, std::move(f));
}

void Development::Stub::async::SetRoute(::grpc::ClientContext* context, const ::protocols::routing::Route* request, ::protocols::development::RouteResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetRoute_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::protocols::development::RouteResponse>* Development::Stub::PrepareAsyncSetRouteRaw(::grpc::ClientContext* context, const ::protocols::routing::Route& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::protocols::development::RouteResponse, ::protocols::routing::Route, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetRoute_, context, request);
}

::grpc::ClientAsyncResponseReader< ::protocols::development::RouteResponse>* Development::Stub::AsyncSetRouteRaw(::grpc::ClientContext* context, const ::protocols::routing::Route& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetRouteRaw(context, request, cq);
  result->StartCall();
  return result;
}

Development::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Development_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Development::Service, ::protocols::routing::Route, ::protocols::development::RouteResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Development::Service* service,
             ::grpc::ServerContext* ctx,
             const ::protocols::routing::Route* req,
             ::protocols::development::RouteResponse* resp) {
               return service->SetRoute(ctx, req, resp);
             }, this)));
}

Development::Service::~Service() {
}

::grpc::Status Development::Service::SetRoute(::grpc::ServerContext* context, const ::protocols::routing::Route* request, ::protocols::development::RouteResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace protocols
}  // namespace development

