// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: development.proto
#ifndef GRPC_development_2eproto__INCLUDED
#define GRPC_development_2eproto__INCLUDED

#include "development.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace protocols {
namespace development {

class Development final {
 public:
  static constexpr char const* service_full_name() {
    return "protocols.development.Development";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status SetRoute(::grpc::ClientContext* context, const ::protocols::routing::Route& request, ::protocols::development::RouteResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::protocols::development::RouteResponse>> AsyncSetRoute(::grpc::ClientContext* context, const ::protocols::routing::Route& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::protocols::development::RouteResponse>>(AsyncSetRouteRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::protocols::development::RouteResponse>> PrepareAsyncSetRoute(::grpc::ClientContext* context, const ::protocols::routing::Route& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::protocols::development::RouteResponse>>(PrepareAsyncSetRouteRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void SetRoute(::grpc::ClientContext* context, const ::protocols::routing::Route* request, ::protocols::development::RouteResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SetRoute(::grpc::ClientContext* context, const ::protocols::routing::Route* request, ::protocols::development::RouteResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::protocols::development::RouteResponse>* AsyncSetRouteRaw(::grpc::ClientContext* context, const ::protocols::routing::Route& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::protocols::development::RouteResponse>* PrepareAsyncSetRouteRaw(::grpc::ClientContext* context, const ::protocols::routing::Route& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status SetRoute(::grpc::ClientContext* context, const ::protocols::routing::Route& request, ::protocols::development::RouteResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::protocols::development::RouteResponse>> AsyncSetRoute(::grpc::ClientContext* context, const ::protocols::routing::Route& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::protocols::development::RouteResponse>>(AsyncSetRouteRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::protocols::development::RouteResponse>> PrepareAsyncSetRoute(::grpc::ClientContext* context, const ::protocols::routing::Route& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::protocols::development::RouteResponse>>(PrepareAsyncSetRouteRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void SetRoute(::grpc::ClientContext* context, const ::protocols::routing::Route* request, ::protocols::development::RouteResponse* response, std::function<void(::grpc::Status)>) override;
      void SetRoute(::grpc::ClientContext* context, const ::protocols::routing::Route* request, ::protocols::development::RouteResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::protocols::development::RouteResponse>* AsyncSetRouteRaw(::grpc::ClientContext* context, const ::protocols::routing::Route& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::protocols::development::RouteResponse>* PrepareAsyncSetRouteRaw(::grpc::ClientContext* context, const ::protocols::routing::Route& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SetRoute_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status SetRoute(::grpc::ServerContext* context, const ::protocols::routing::Route* request, ::protocols::development::RouteResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_SetRoute : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SetRoute() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SetRoute() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetRoute(::grpc::ServerContext* /*context*/, const ::protocols::routing::Route* /*request*/, ::protocols::development::RouteResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSetRoute(::grpc::ServerContext* context, ::protocols::routing::Route* request, ::grpc::ServerAsyncResponseWriter< ::protocols::development::RouteResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SetRoute<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_SetRoute : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SetRoute() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::protocols::routing::Route, ::protocols::development::RouteResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::protocols::routing::Route* request, ::protocols::development::RouteResponse* response) { return this->SetRoute(context, request, response); }));}
    void SetMessageAllocatorFor_SetRoute(
        ::grpc::MessageAllocator< ::protocols::routing::Route, ::protocols::development::RouteResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::protocols::routing::Route, ::protocols::development::RouteResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SetRoute() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetRoute(::grpc::ServerContext* /*context*/, const ::protocols::routing::Route* /*request*/, ::protocols::development::RouteResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SetRoute(
      ::grpc::CallbackServerContext* /*context*/, const ::protocols::routing::Route* /*request*/, ::protocols::development::RouteResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_SetRoute<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_SetRoute : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SetRoute() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SetRoute() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetRoute(::grpc::ServerContext* /*context*/, const ::protocols::routing::Route* /*request*/, ::protocols::development::RouteResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_SetRoute : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SetRoute() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_SetRoute() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetRoute(::grpc::ServerContext* /*context*/, const ::protocols::routing::Route* /*request*/, ::protocols::development::RouteResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSetRoute(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SetRoute : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SetRoute() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SetRoute(context, request, response); }));
    }
    ~WithRawCallbackMethod_SetRoute() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetRoute(::grpc::ServerContext* /*context*/, const ::protocols::routing::Route* /*request*/, ::protocols::development::RouteResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SetRoute(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SetRoute : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SetRoute() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::protocols::routing::Route, ::protocols::development::RouteResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::protocols::routing::Route, ::protocols::development::RouteResponse>* streamer) {
                       return this->StreamedSetRoute(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SetRoute() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SetRoute(::grpc::ServerContext* /*context*/, const ::protocols::routing::Route* /*request*/, ::protocols::development::RouteResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSetRoute(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::protocols::routing::Route,::protocols::development::RouteResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_SetRoute<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_SetRoute<Service > StreamedService;
};

}  // namespace development
}  // namespace protocols


#endif  // GRPC_development_2eproto__INCLUDED
