name: Build and Test
on: push
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v1
      - run: sudo apt-get install -y valgrind
      - run: pip3 install --user gcovr
      - run: pip3 install --user ninja
      - run: pip3 install --user meson
      - uses: actions/checkout@v2
      - run: meson setup build -Db_coverage=true
        env:
          CC: gcc
          CXX: g++
      - run: meson setup build_clang -Db_coverage=true
        env:
          CC: clang
          CXX: clang++
      - run: meson compile -C build
      - run: meson compile -C build_clang
      - run: ./build/test/tests
      - run: ninja coverage-xml -C build # `meson coverage` doesn't work
      - uses: codecov/codecov-action@v2
        with:
          files: ./build/meson-logs/coverage.xml
      - run: valgrind -v --error-exitcode=1 --leak-check=full --show-leak-kinds=all --track-origins=yes ./build/test/tests
