name: Build and Test
on: push
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v1
      - run: sudo apt-get install -y valgrind
      - run: pip3 install --user gcovr
      - uses: actions/checkout@v2
      - uses: BSFishy/meson-build@v1.0.3
        with:
          action: build
      - run: ./build/test/sim/simtest
      - run: gcovr --root build/src --xml-pretty -o coverage.xml
      - uses: codecov/codecov-action@v2
        with:
          files: ./coverage.xml
      - run: valgrind -v --leak-check=full --show-leak-kinds=all --track-origins=yes ./build/test/sim/simtest
